steps:
  #- name: 'gcr.io/cloud-builders/mvn'
   # args: ['test']
    #id: 'run-tests'

  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    id: 'build-jar'
    #waitFor: ['run-tests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']
    id: 'build-container'
    waitFor: [ 'build-jar' ]

substitutions:
  _SERVICE_NAME: LaMontagne.API

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'