steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['test']
    id: 'run-tests'

  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    id: 'build-jar'
    waitFor: ['run-tests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA', '.']
    id: 'build-container'
    waitFor: ['build-jar']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']
    id: 'push-container'
    waitFor: ['build-container']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--min-instances'
      - '0'
      - '--memory'
      - '512Mi'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod'
    id: 'deploy'
    waitFor: ['push-container']

substitutions:
  _SERVICE_NAME: LaMontagne.API
  _REGION: europe-west9

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'         # speed up the build

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'