spring:
  application:
    name: LaMontagne.API
  data:
    mongodb:
      uri: ${MONGO_URL}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  profiles:
    active: dev

meteo:
  meteoblue:
    url: ${METEOBLUE_URL}
    apikey: ${METEOBLUE_API_KEY}
  meteofrance:
    url: ${METEOFRANCE_URL}
    apikey: ${METEOFRANCE_API_KEY}

app:
  cloudinary:
    url: ${CLOUDINARY_URL}
  security:
    jwt:
      secret: ${JWT_SECRET}
  meteo:
    providers:
      meteoblue:
        enabled: true
      meteofrance:
        enabled: true
  data:
    massifs:
      geojsonFile: /data/Metadata_massif_DP_2024_20240215.geojson