spring:
  data:
    mongodb:
      uri: ${MONGO_URL}

meteo:
  meteoblue:
    url: ${METEOBLUE_URL}
    apikey: ${METEOBLUE_API_KEY}
  meteofrance:
    url: ${METEOFRANCE_URL}
    apikey: ${METEOFRANCE_API_KEY}

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
  cloudinary:
    url: ${CLOUDINARY_URL}