spring:
  application:
    name: LaMontagne.API
  data:
    mongodb:
      uri: ${MONGO_URL}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  profiles:
    active: dev

app:
  cloudinary:
    url: ${CLOUDINARY_URL}
  security:
    jwt:
      secret: ${JWT_SECRET}